language: node_js

node_js:
  - "stable"

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: firebase
  edge: true
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $PROJECT_ID

